name: Beatmap

settings:
  base:
    SWIFT_VERSION: '5.1'
    ENABLE_BITCODE: NO
  configs:
    Release:
      SWIFT_COMPILATION_MODE: 'wholemodule'

options:
  bundleIdPrefix: com.beatmap
  xcodeVersion: 11.3.1
  usesTabs: false
  indentWidth: 4
  deploymentTarget:
    iOS: 13.0

targets:
  BeatmapAR:
    type: application
    platform: iOS
    info:
      path: BeatmapAR/Info.plist
      properties:
        CFBundleDisplayName: $(DISPLAY_NAME)
        UIUserInterfaceStyle: Light
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        ITSAppUsesNonExemptEncryption: false
        NSCameraUsageDescription: BeatmapAR needs access to your camera to display the AR experience.
        UIAppFonts:
         - Teko-Bold.ttf
         - Teko-Light.ttf
         - Teko-Medium.ttf
         - Teko-Regular.ttf
         - Teko-SemiBold.ttf
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: false
        CFBundleDocumentTypes:
         - CFBundleTypeName: Zip archive
           CFBundleTypeRole: Editor
           LSHandlerRank: Owner
           LSItemContentTypes:
            - com.pkware.zip-archive
           UTTypeTagSpecification:
             public.filename-extension: zip
             public.mime-type: application/zip
    sources:
      - path: README.md
        buildPhase: none
      - path: BeatmapAR
        createIntermediateGroups: true
        excludes:
         - "Assets/Fonts/Teko/OFL.txt"
      - path: BeatmapAR/Assets/Fonts/Teko/OFL.txt
        createIntermediateGroups: true
        buildPhase: none
    dependencies:
      - target: BeatmapLoader
      - carthage: ZIPFoundation
      - target: APAudioPlayer
    preBuildScripts:
      - name: Generate Warnings
        script: |
                if [ "${CONFIGURATION}" = "Debug" ]; then
                  TAGS="TODO:|FIXME:"
                  find "${PROJECT_DIR}/BeatmapAR" \( -name "*.h" -or -name "*.m" -or -name "*.swift" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/"
                fi
      - name: Swift Lint
        script: |
                if which swiftlint >/dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi

  BeatmapLoader:
    type: framework
    platform: iOS
    sources:
      - path: BeatmapLoader
        createIntermediateGroups: true
    preBuildScripts:
      - name: Generate Warnings
        script: |
                if [ "${CONFIGURATION}" = "Debug" ]; then
                  TAGS="TODO:|FIXME:"
                  find "${PROJECT_DIR}/BeatmapLoader" \( -name "*.h" -or -name "*.m" -or -name "*.swift" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/"
                fi
      - name: Swift Lint
        script: |
                if which swiftlint >/dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi

  BeatmapLoaderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BeatmapLoaderTests
        createIntermediateGroups: true
    dependencies:
      - target: BeatmapLoader
      - carthage: ZIPFoundation

  APAudioPlayer:
    type: framework
    platform: iOS
    settings:
      OTHER_LDFLAGS: -ObjC
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)/APAudioPlayer/bass
    sources:
      - path: APAudioPlayer
        createIntermediateGroups: true
        excludes:
         - "bass"
      - path: APAudioPlayer/bass/bass.h
        createIntermediateGroups: true
        buildPhase: headers
        headerVisibility: private
      - path: APAudioPlayer/bass/libbass.a
        createIntermediateGroups: true
        buildPhase: none
    dependencies:
     - framework: libbass.a
       link: true
       embed: false
     - sdk: AVFoundation.framework
     - sdk: AudioToolbox.framework
     - sdk: SystemConfiguration.framework
     - sdk: CFNetwork.framework
     - sdk: Accelerate.framework

schemes:
  BeatmapAR:
    build:
      targets:
        BeatmapAR: all
  BeatmapLoader:
    build:
      targets:
        BeatmapLoader: all
    test:
      gatherCoverageData: true
      targets:
        - BeatmapLoaderTests
